{
  config,
  ...
}:

{
  home.username = "huon";
  home.homeDirectory = "/home/huon";
  home.stateVersion = "26.05";

  imports = [
    # ./specialisations/gdm
    ./packages

    # This is temporary until I figure out how to switch specialisations properly
    ../system/display/gnome/dconf.nix # auto generated by dconf2nix
    ../system/display/gnome/dconf-custom.nix # handwritten dconf settings
  ];

  home.file."${config.home.homeDirectory}/.themes/custom".source =
    "${config.home.homeDirectory}/nixos/dots/gnome-themes/custom";

  # home.file.".config/<app>".source = ./config/<app>;
}
