{ pkgs, ... }:

{
  # This is temporary until I figure out how to switch specialisations properly
  home-manager.users.huon.imports = [
    ./dconf.nix # auto generated by dconf2nix
    ./dconf-custom.nix # handwritten dconf settings
  ];

  # Enable the GNOME desktop environment.
  services.displayManager.gdm.enable = true;
  services.desktopManager.gnome.enable = true;
  services.gnome.games.enable = false;

  # remove bloat
  environment.gnome.excludePackages = with pkgs; [
    gnome-calculator
    gnome-contacts
    gnome-maps
    gnome-software
    epiphany
    yelp
    gnome-weather
    gnome-tour
  ];
}
